version: '3.9'

services:

  web_server_db:
    image: web_server_db
    build:
      context: web_server/db
    container_name: web_server_db
    restart: always
    ports:
      - 6932:5432
    volumes:
      - web_server_db:/var/lib/postgresql/data

  crawler_queue:
    image: crawler_queue
    build:
      context: crawler_queue
    container_name: crawler_queue
    restart: always
    ports:
      - 6381:6379
    volumes:
      - ./crawler_queue/redis.conf:/usr/local/etc/redis/redis.conf
      - crawler_queue_data:/data

  crawler_api:
    image: crawler_api
    build:
      context: web_server
    container_name: crawler_api
    depends_on:
      - web_server_db
      - crawler_queue
    env_file:
      - web_server/.env
    ports:
      - 9060:8000
    volumes:
      - ./common:/workspaces/web_server/common:rw
      - ./applications:/workspaces/web_server/applications:rw

  crawler_worker:
    image: crawler_worker
    build:
      context: worker
      dockerfile: Dockerfile
    depends_on:
      - web_server_db
      - crawler_queue
    env_file:
      - worker/.env
    volumes:
      - ./common:/workspaces/worker/common:rw
      - ./applications:/workspaces/worker/applications:rw

  crawler_worker_monitor:  
    image: mher/flower
    container_name: crawler_worker_monitor
    environment:
      - CELERY_BROKER_URL=redis://crawler_queue:6379/0
      - FLOWER_PORT=8888
      - FLOWER_URL_PREFIX=flower
    ports:  
      - 8888:8888

volumes:
  web_server_db:
  crawler_queue_data:
