version: '3.9'

services:

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_USER=$MY_DB_USER
      - MYSQL_ROOT_PASSWORD=$MY_DB_PASSWORD
      - MYSQL_DATABASE=$MY_DB_NAME
    ports:
      - 3310:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HOST_VOLS/db/var/lib/mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_ROOT_USER --password=$MY_DB_PASSWORD
      timeout: 20s
      retries: 3

  crawler_queue:
    image: redis
    container_name: crawler_queue
    command: redis-server --include /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 6380:6379
    volumes:
      - $HOST_VOLS/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - $HOST_VOLS/redis/data:/data

  crawler_api:
    image: crawler_api
    build:
      context: .
    container_name: crawler_api
    depends_on:
      - db
      - crawler_queue
    env_file:
      - .env
    ports:
      - 9060:8000

  crawler_worker:
    image: crawler_worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - db
      - crawler_queue
    env_file:
      - worker/.env