# Generated by Django 4.0.3 on 2022-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblinkcontent',
            name='status_code',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
